-- 다중행 함수(그룹 함수) : 하나의 열에 출력 결과를 담는 다중행 함수
-- SUM(컬럼) / COUNT(컬럼)
SELECT COUNT(*), COUNT(COMM) FROM EMP; -- 자동으로 NULL값 제외하고 COUNT
SELECT SUM(SAL), SUM(COMM) FROM EMP; -- 자동으로 NULL값 제외하고 SUM
SELECT SUM(SAL), SUM(COMM) FROM EMP WHERE COMM IS NULL;

-- MAX(컬럼) / MIN(컬럼) / AVG(컬럼)
SELECT MAX(SAL), MIN(SAL) FROM EMP;

-- Q. 급여를 제일 많이 받는 사원의 정보 출력
SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);
-- Q. 20번 부서의 직원 수
SELECT COUNT(*) FROM EMP WHERE DEPTNO = 20;
SELECT ENAME, COUNT(*) FROM EMP WHERE DEPTNO = 20; -- ORA-0093 : not a single-group group function

-- GROUP BY
SELECT DEPTNO, COUNT(*), SUM(SAL) FROM EMP group by DEPTNO;
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL) FROM EMP group by DEPTNO, JOB;

SELECT DEPTNO, COUNT(*), SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL) > 2000;
SELECT DEPTNO, COUNT(*), SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING DEPTNO = 10;

-- ROLLUP, CUBE
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL) FROM EMP group by ROLLUP(DEPTNO, JOB);
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL) FROM EMP group by CUBE(DEPTNO, JOB);

-- GROUPING SETS / GROUPING - 0(그룹화O), 1(그룹화X) / GROUPING_ID
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL) FROM EMP GROUP BY GROUPING SETS (DEPTNO, JOB);
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL), GROUPING(DEPTNO), GROUPING(JOB) 
FROM EMP group by CUBE(DEPTNO, JOB);
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL), GROUPING(DEPTNO), GROUPING(JOB), GROUPING_ID(DEPTNO,JOB) 
FROM EMP group by CUBE(DEPTNO, JOB);

-- LISTAGG 
SELECT DEPTNO, ENAME FROM EMP GROUP BY DEPTNO, ENAME ORDER BY DEPTNO;
SELECT DEPTNO, LISTAGG(ENAME,',') WITHIN GROUP(ORDER BY SAL DESC) NAMES FROM EMP GROUP BY DEPTNO;

-- PIVOT / UNPIVOT
SELECT DEPTNO, JOB, MAX(SAL) FROM EMP GROUP BY DEPTNO, JOB;
/*
SELECT *
FROM (피벗 대상 쿼리문)
PIVOT (그룹함수(컬럼) FOR 피벗컬럼 IN(컬럼 값1, 컬럼 값2…)
*/
SELECT *
FROM (SELECT DEPTNO, JOB, SAL FROM EMP)
PIVOT(MAX(SAL) FOR DEPTNO IN (10,20,30))
ORDER BY JOB;

SELECT *
FROM (SELECT JOB, DEPTNO, SAL FROM EMP)
PIVOT (MAX(SAL) FOR JOB IN('CLERK','SALESMAN','PRESIDENT','ANALYST','MANAGER'));

SELECT *
FROM(SELECT DEPTNO,
     MAX(DECODE(JOB, 'CLERK', SAL)) AS "CLERK",
     MAX(DECODE(JOB, 'SALESMAN', SAL)) AS "SALESMAN",
     MAX(DECODE(JOB, 'PRESIDENTK', SAL)) AS "PRESIDENT",
     MAX(DECODE(JOB, 'ANALYST', SAL)) AS "ANALYST",
     MAX(DECODE(JOB, 'MANAGER', SAL)) AS "MANAGER"
     FROM EMP
     GROUP BY DEPTNO
     ORDER BY DEPTNO)
UNPIVOT(SAL FOR JOB IN (CLERK, SALESMAN, PRESIDENT, ANALYST, MANAGER))
ORDER BY DEPTNO, JOB;

SELECT *
FROM (SELECT JOB, TO_CHAR(HIREDATE,'FMMM')||'월' HIREMONTH FROM EMP)
PIVOT (COUNT(*) FOR HIREMONTH IN('1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'))
ORDER BY JOB;


