-- TRANSACTION / TCL : TRANSACTION CONTROL LANGUAGE
-- DEPT테이블을 복사한 DEPT_TCL테이블 작성
CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL
VALUES (50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL
SET LOC='BUSAN' WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

SELECT * FROM DEPT_TCL;

ROLLBACK;

-- SAVEPOINT
DELETE FROM DEPT_TCL WHERE DEPTNO = 40;
COMMIT;
DELETE FROM DEPT_TCL WHERE DEPTNO = 30;
SAVEPOINT C1;
DELETE FROM DEPT_TCL WHERE DEPTNO = 20;
SAVEPOINT C2;
DELETE FROM DEPT_TCL WHERE DEPTNO = 10;

ROLLBACK TO C2;
ROLLBACK TO C1;
ROLLBACK;

DELETE FROM DEPT_TCL WHERE DEPTNO = 30;
COMMIT;

UPDATE DEPT_TCL 
SET LOC = 'SEOUL' WHERE DEPTNO = 20;






