-- DML(데이터 조작어, DATA MANIPULATION LANGUAGE) 
-- INSERT, UPDATE, DELETE

-- INSERT INTO 테이블 이름[열1,열2,...] >> 모든 열에 다 넣을 경우 [] 생략가능.
-- VALUES (열1데이터, 열2데이터, ...);  새로운 ROW가 만들어짐.

CREATE TABLE TEMP_DEPT AS SELECT * FROM DEPT; -- 똑같이 생긴 테이블 복사
SELECT * FROM TEMP_DEPT; 
CREATE TABLE TEMP_EMP AS SELECT * FROM EMP WHERE 1=0; -- 구조(스키마)만 복사한 테이블 생성
DROP TABLE TEMP_EMP; -- 휴지통에 테이블 삭제
DROP TABLE TEMP_EMP PURGE; -- 영구 삭제
SELECT * FROM TAB; -- 계정 안에 있는 모든 테이블 검색.

-- 50, DATABASE, SEOUL
INSERT INTO TEMP_DEPT(DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE','SEOUL');

SELECT * FROM TEMP_DEPT;

-- 60, 'R&D','JEJU'
SET ESCAPE ON;
INSERT INTO TEMP_DEPT
VALUES (60, 'R\&D','JEJU');

DELETE FROM TEMP_DEPT WHERE DEPTNO = 60;

-- NULL 데이터 입력 : 명시적 OR 암시적
-- 70, 'IT', NULL (명시)
INSERT INTO TEMP_DEPT
VALUES(70, 'IT', NULL);

-- 80, 'IT2', NULL (암시)
INSERT INTO TEMP_DEPT (DEPTNO, DNAME)
VALUES (80, 'IT2');

CREATE TABLE TEMP_EMP AS SELECT * FROM EMP WHERE 1=0;
SELECT * FROM TEMP_EMP;
DESC TEMP_EMP;

-- 테이블에 날짜 데이터 입력 : 직접 입력 / TO_DATE / SYSDATE
INSERT INTO TEMP_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999,'홍길동', 'PRESIDENT', NULL, '2021/11/22', 5000, 1000, 10); -- YYYY/MM/DD 지정된 형식

INSERT INTO TEMP_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1111,'성춘향', 'MANAGER', 9999, '2021-11-22', 4000, NULL, 20); -- YYYY-MM-DD 지정된 형식

INSERT INTO TEMP_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (2222,'이순신', 'MANAGER', 9999,TO_DATE('22/11/2021','DD/MM/YYYY'), 4000, NULL, 20); -- TO_DATE

INSERT INTO TEMP_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (3333,'심청', 'MANAGER', 9999, SYSDATE , 4000, NULL, 30); -- SYSDATE

SELECT * FROM TEMP_EMP;

-- 서브쿼리 사용하여 한 번에 여러 데이터 추가하기
INSERT INTO TEMP_EMP 
SELECT * FROM EMP WHERE DEPTNO = 10;

INSERT INTO TEMP_EMP (EMPNO, ENAME, DEPTNO)
SELECT EMPNO, ENAME, DEPTNO FROM EMP WHERE DEPTNO = 20;
COMMIT;
-- UPDATE : 데이터 수정
-- UPDATE [변경할 테이블]
-- SET [변경할 열1]=[데이터], ... WHERE[ 데이터를 변경할 대상 행 선별 조건];
UPDATE TEMP_DEPT
SET LOC = 'SEOUL'
WHERE DEPTNO = 70;

SELECT * FROM TEMP_DEPT;

-- 서브쿼리로 데이터 수정 / 80부서의 부서명과 위치를 60부서의 위치로 수정
UPDATE TEMP_DEPT
SET (DNAME, LOC) = (SELECT DNAME, LOC FROM TEMP_DEPT WHERE DEPTNO = 60)
WHERE DEPTNO = 80;

-- 삭제 DELETE FROM [테이블 명] WHERE 조건
-- 80번 부서 삭제
DELETE FROM TEMP_DEPT
WHERE DEPTNO = 80;


