-- VIEW
-- CREATE [OR REPLACE] [FORCE | NOFORCE] VIEW 뷰 이름 [(열 이름1, 열 이름2...)]
-- AS (저장할 SELECT문)
-- [WITH CHECK OPTION [CONSTRAINT 제약 조건]]
-- [WITH READ ONLY [CONSTRAINT 제약 조건]];

CREATE VIEW EMP20 
AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO=20);

SELECT * FROM EMP20;

SELECT * FROM USER_VIEWS;

CREATE VIEW EMP_INFO(사원번호, 사원명, 부서명, 급여)
AS (SELECT EMPNO, ENAME, DNAME, SAL FROM EMP NATURAL JOIN DEPT);

SELECT * FROM EMP_INFO WHERE 사원번호=7788;

CREATE OR REPLACE FORCE VIEW VIEW_NOTABLE 
AS SELECT * FROM EMP02 WHERE DEPTNO=10;

DROP TABLE EMP01 PURGE;
CREATE TABLE EMP01 AS SELECT * FROM EMP;

SELECT * FROM EMP01;

CREATE OR REPLACE VIEW VIEW_CHK20
AS
SELECT EMPNO, ENAME, SAL, COMM, DEPTNO FROM EMP01
WHERE DEPTNO = 20 WITH CHECK OPTION; -- 부서번호에 CHECK옵션을 지정, VIEW를 통해서는 부서번호 변경X

SELECT * FROM VIEW_CHK20;

UPDATE VIEW_CHK20 SET SAL = 10 WHERE SAL >=3000;

CREATE OR REPLACE VIEW VIEW_30
AS SELECT EMPNO, ENAME, SAL, DEPTNO, COMM FROM EMP01 
WHERE DEPTNO=30 WITH READ ONLY;

SELECT * FROM VIEW_30;
UPDATE VIEW_30 SET COMM = 1000;

-- VIEW 삭제 : DROP
DROP VIEW VIEW_NOTABLE;

-- 급여 TOP3 출력
SELECT EMPNO, ENAME, SAL, ROWNUM
FROM (SELECT * FROM EMP ORDER BY SAL DESC)
WHERE ROWNUM < 4;

SELECT ROWNUM, E.*
FROM (SELECT * FROM EMP ORDER BY SAL DESC) E
WHERE ROWNUM < 4;

-- 급여 TOP3~5 출력
SELECT E2.* FROM
(SELECT ROWNUM R, E1.*
FROM (SELECT * FROM EMP ORDER BY SAL DESC) E1) E2
WHERE R BETWEEN 3 AND 5;
