SELECT * FROM BOOK;
SELECT * FROM IMPORTED_BOOK;

-- 1
INSERT INTO BOOK 
VALUES (11, '스포츠 의학', '한솔의학서적',90000);

-- 2
INSERT INTO BOOK
VALUES (14, '스포츠 의학', '한솔의학서적', NULL);

-- 3
INSERT INTO BOOK
SELECT * FROM IMPORTED_BOOK;

-- 4
UPDATE BOOK
SET PUBLISHER = '대한출판사'
WHERE PUBLISHER = '대한미디어';

SELECT * FROM CUSTOMER;

-- 5
UPDATE CUSTOMER
SET ADDRESS = '대한민국 부산'
WHERE CUSTID = 5;

-- 6
UPDATE CUSTOMER
SET ADDRESS =(SELECT ADDRESS FROM CUSTOMER WHERE NAME = '김연아')
WHERE NAME = '박세리';

-- 7 
DELETE FROM BOOK
WHERE PUBLISHER = '삼성당';

-- 8
DELETE FROM CUSTOMER
WHERE CUSTID = 5;

-- 9 ORA-02292: 무결성 제약조건(C##MADANG.SYS_C007506)이 위배되었습니다- 자식 레코드가 발견되었습니다
DELETE FROM CUSTOMER;

ROLLBACK;
SELECT * FROM CUSTOMER;


